######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 3 09:22:39 2016
######################################################################
TEMPLATE = lib
CONFIG += staticlib
DEPENDPATH += .
INCLUDEPATH += .

QT += sql

# Input
HEADERS += sqlitedb.h
SOURCES += sqlitedb.cpp
